In [1]:
import torch

In [2]:
# Sample 2D tensor (matrix)
tensor = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [4]:
#
# Create a mask based on the condition on the first column
mask = tensor[:, 0] > 3

# Apply the mask to select the rows that meet the condition
filtered_tensor = tensor[mask]
print(mask)

print(filtered_tensor)
# Output: tensor([[4, 5, 6],
#                 [7, 8, 9]])

tensor([False,  True,  True])
tensor([[4, 5, 6],
        [7, 8, 9]])


In [5]:
# Create a mask based on the condition in the first row
column_mask = tensor[0, :] > 1

# Apply the mask to select the columns that meet the condition
filtered_tensor = tensor[:, column_mask]

print(filtered_tensor)
# Output: tensor([[2, 3],
#                 [5, 6],
#                 [8, 9]])

tensor([[2, 3],
        [5, 6],
        [8, 9]])


In [ ]:
# Use masked_select with reshaping, here filtering based on the first column as before
mask = tensor[:, 0] > 3
filtered_tensor = torch.masked_select(tensor, mask.unsqueeze(1)).view(-1, tensor.size(1))
print(filtered_tensor)
# Output: tensor([[4, 5, 6],
#                 [7, 8, 9]])

tensor([[False],
        [ True],
        [ True]])


AttributeError: 'NoneType' object has no attribute 'view'