In [1]:
import torch

In [23]:
# # Create a tensor
# tensor = torch.Tensor([[1,1,1,1],[2,2,2,1],[1,1,1,2],[2,2,2,3]])
# print(tensor)

# # slice by 4th column value
# idx = (tensor[tensor[:,3].type(torch.int8)==1, :3])
# print(idx)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 1.],
        [1., 1., 1., 2.],
        [2., 2., 2., 3.]])


In [2]:
input = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
indices = torch.tensor([0,1,2,0])
# expected output [1,5,9,10]
output = torch.tensor([input[i, indices[i]] for i in range(indices.shape[0])])
print(output)

tensor([ 1,  5,  9, 10])


In [12]:
input = torch.tensor([[1,1,2,2,3],[2,2,3,3,3],[1,2,3,3,3],[1,1,3,3,3]])
mask_vals = torch.tensor([1, 3, 2, 2])
# expected output [[T,T,F,F,F],[F,F,T,T,T],[F,T,F,F,F],[F,F,F,F,F]]
mask = mask_vals.unsqueeze(1).expand(-1, input.shape[1])
print(input==mask)

tensor([[ True,  True, False, False, False],
        [False, False,  True,  True,  True],
        [False,  True, False, False, False],
        [False, False, False, False, False]])
