In [1]:
import torch
torch.__version__

## Ways to compile functions

In [3]:
# calling torch.compile()
def foo(x, y):
    a = torch.sin(x)
    b = torch.cos(y)
    return a + b
opt_foo1 = torch.compile(foo)
print(opt_foo1(torch.randn(10, 10), torch.randn(10, 10)))

tensor([[ 1.6043, -0.2746,  1.7431,  0.4415,  0.9408, -0.4355,  1.6645,  1.6300,
          1.3092,  0.2094],
        [ 0.5522,  1.1827,  1.4101,  0.3985,  1.1439,  1.1584,  1.6066,  1.4491,
          1.4636, -0.9000],
        [ 0.4810,  0.4645, -0.4017,  1.3124,  1.4241,  0.2296,  1.2549, -0.6780,
          1.6899,  1.7346],
        [ 1.5717,  0.0319,  1.1183,  1.6153, -0.9053, -0.2714, -0.2103,  1.4175,
          0.3798,  0.9044],
        [ 0.7737,  0.3309,  1.4537,  0.5419,  0.1800,  1.1207,  0.9242, -0.4284,
          0.5850, -0.0317],
        [-0.0140,  1.7241,  1.0403, -0.0819, -0.1942,  1.7794,  1.2810,  1.9000,
          0.8102,  1.5944],
        [-0.1889, -0.6406,  0.3374,  0.4559,  1.2599,  1.8972,  0.1821,  1.9660,
          1.1527,  0.5869],
        [-1.0972, -0.4314,  1.1855,  1.6278, -0.8319,  1.2264,  0.5447,  0.8260,
          0.5960,  0.8217],
        [-0.5196,  1.0953,  1.3367, -0.0828, -0.0024,  0.1470,  0.0420,  1.7272,
         -0.2125,  1.0458],
        [ 1.4449,  

In [4]:
# use decorator
@torch.compile
def opt_foo2(x, y):
    a = torch.sin(x)
    b = torch.cos(y)
    return a + b
print(opt_foo2(torch.randn(10, 10), torch.randn(10, 10)))

tensor([[-0.1912, -0.1721,  0.8253, -1.0740, -1.0621, -0.0351,  0.6220,  1.4802,
          0.2999,  1.0384],
        [ 0.3367,  0.1423,  0.5219, -0.1880, -0.5841,  0.5742,  1.5125, -1.3998,
          1.2686,  1.9325],
        [ 0.2175,  0.6827,  0.6337,  0.5219,  1.3809,  1.1769,  1.4833,  0.8134,
          1.8649,  0.4727],
        [-0.1467,  0.7379, -1.3032,  0.0285,  0.5850,  0.1769, -0.9247,  1.3094,
          1.0439,  1.5132],
        [ 0.6849,  0.0824,  0.6481,  1.1109,  0.9985,  1.4045,  0.1878, -0.7976,
          0.4602,  1.3794],
        [ 1.8323,  1.4994,  0.3880,  1.7921,  0.0601,  0.4286,  0.3825,  0.0391,
         -0.1501,  0.9742],
        [ 0.2798, -0.1901, -0.2974,  1.1973, -0.4259,  1.4623, -0.3657,  0.3740,
          0.0027, -0.0205],
        [ 1.0297,  1.3408, -0.0384,  1.8761,  1.9399, -0.6877, -0.0485,  0.0711,
          1.1092,  1.0371],
        [ 0.7977,  1.2743, -0.1078,  0.2799, -0.6749,  1.3553,  0.3130,  0.8614,
          1.2505,  1.3905],
        [ 1.5664,  

In [5]:
# compile torch.nn.Module
class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.lin = torch.nn.Linear(100, 10)

    def forward(self, x):
        return torch.nn.functional.relu(self.lin(x))

mod = MyModule()
opt_mod = torch.compile(mod)
print(opt_mod(torch.randn(10, 100)))

tensor([[0.0340, 0.2678, -0.0000, 0.2469, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000,
         -0.0000],
        [-0.0000, 0.3892, -0.0000, 0.3505, 0.0731, 0.1244, -0.0000, -0.0000, 0.5205,
         -0.0000],
        [0.1470, -0.0000, -0.0000, 0.1113, -0.0000, -0.0000, 0.3741, -0.0000, -0.0000,
         0.0328],
        [-0.0000, 0.5501, 0.2239, -0.0000, 0.0484, -0.0000, 0.0893, 0.5620, -0.0000,
         0.6922],
        [1.3632, 0.5130, -0.0000, 0.1752, 1.0213, -0.0000, 0.0653, -0.0000, 0.7644,
         -0.0000],
        [0.1039, 0.2425, 0.3622, 0.3732, 0.4868, -0.0000, -0.0000, 0.3979, -0.0000,
         0.5545],
        [-0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, 0.4019, -0.0000, -0.0000,
         -0.0000],
        [0.2069, 0.4298, -0.0000, -0.0000, -0.0000, 0.3999, -0.0000, -0.0000, 0.1561,
         0.1818],
        [0.3223, -0.0000, -0.0000, 0.1642, 0.9643, -0.0000, -0.0000, 0.5988, -0.0000,
         -0.0000],
        [0.9123, 0.1878, -0.0000, 0.8782, -0.0000, -0.0000, 

## Demonstrate Speedup

In [6]:
# Returns the result of running `fn()` and the time it took for `fn()` to run,
# in seconds. We use CUDA events and synchronization for the most accurate
# measurements.
def timed(fn):
    start = torch.cuda.Event(enable_timing=True)
    end = torch.cuda.Event(enable_timing=True)
    start.record()
    result = fn()
    end.record()
    torch.cuda.synchronize()
    return result, start.elapsed_time(end) / 1000

# Generates random input and targets data for the model, where `b` is
# batch size.
def generate_data(b):
    return (
        torch.randn(b, 3, 128, 128).to(torch.float32).cuda(),
        torch.randint(1000, (b,)).cuda(),
    )

N_ITERS = 10

from torchvision.models import densenet121
def init_model():
    return densenet121().to(torch.float32).cuda()